app {
  name = "EcommerceAnalytics"

  spark {
    master = "local[*]"
    shuffle-partitions = 8
  }

  data {
    input {
      transactions = "src/main/resources/data/transactions.csv"
      users        = "src/main/resources/data/users.json"
      products     = "src/main/resources/data/products.parquet"
      merchants    = "src/main/resources/data/merchants.csv"
    }
    output {
      directory = "output"
    }
  }
}
